baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://jsbusmc.github.io" # the base hostname & protocol for your site.
title: "jsbUSMC | John S. Bissonette"

paginate: 10 #articles per page
paginate_path: /blog/page:num #makes pagination working

#contacts
git: "https://github.com/jsbUSMC"  #your github url here.
stackoverflow: "http://stackoverflow.com/users/4743465/john-bissonette" #Add your stackoverflow url here.
twitter: "https://twitter.com/DennisQua1d"  #Add your twitter url here.
linkedin: "https://linkedin.com/in/john-bissonette"


#disqus comment
disqus:
    shortname: "test" #your disqus comment short name

#google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
